package br.com.mackenzie.peladafc.model;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : PeladaFC
//  @ File Name : Jogador.java
//  @ Date : 07/09/2013
//  @ Author : 
//
//




/** */
public class Jogador {
	/** */
	private int id;
	
	/** */
	private String nome;
	
	/** */
	private String apelido;
	
	/** */
	private int classificao;
	
	public Jogador() {
		// TODO Auto-generated constructor stub
		this.setNome("");
		this.setApelido("");
		this.setClassificao(0);
	}
	
	public Jogador(String nome, String apelido, int classificao) {
		// TODO Auto-generated constructor stub
		this.setNome(nome);
		this.setApelido(apelido);
		this.setClassificao(classificao);
	}
	
	public int getId() {
		return id;
	}

	public void setId(int id) {
		this.id = id;
	}
	
	public String getNome() {
		return nome;
	}

	public void setNome(String nome) {
		this.nome = nome;
	}

	public String getApelido() {
		return apelido;
	}

	public void setApelido(String apelido) {
		this.apelido = apelido;
	}

	public int getClassificao() {
		return classificao;
	}

	public void setClassificao(int classificao) {
		this.classificao = classificao;
	}

	@Override
	public String toString() {
		return nome + " (" + apelido + ")";
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + id;
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		Jogador other = (Jogador) obj;
		if (id != other.id)
			return false;
		return true;
	}
}
